
#define VS_VERSION_INFO                 1
#define IDD_ABOUT                       101
#define IDD_HASH                        102
#define IDD_RANDOM                      103
#define IDI_ICON1                       103
#define IDD_PREFERENCES                 104
#define IDD_CRYPT                       105
#define IDB_BITMAP1                     105
#define IDD_CRYPT_BASIC                 106
#define IDD_CRYPT_AUTH                  107
#define IDD_CRYPT_KEY                   108
#define IDD_CRYPT_IV                    109
#define IDD_AUTH                        110
#define IDD_CONVERT                     111
#define IDD_CRYPT_ENCODING              112
#define IDD_INITDATA                    113
#define IDC_OK                          998
#define IDC_CANCEL                      999
#define IDC_CRYPT_TAB                   1000
#define IDC_HASH_ALGO                   1000
#define IDC_RANDOM_EDIT                 1000
#define IDC_PREF_FILES_ENABLE           1000
#define IDC_AUTH_KEY                    1000
#define IDC_ABOUT_CERBERUS_URL          1000
#define IDC_CRYPT_ENC_ASCII             1001
#define IDC_HASH_ENC_ASCII              1001
#define IDC_RANDOM_SPIN                 1001
#define IDC_PREF_FILES_EXT              1001
#define IDC_AUTH_SHOW                   1001
#define IDC_CRYPT_ENC_HEX               1002
#define IDC_RANDOM_R1                   1002
#define IDC_PREF_FILES_ASK              1002
#define IDC_COMBO1                      1002
#define IDC_HASH_KEYLIST                1002
#define IDC_CRYPT_ENC_BASE64            1003
#define IDC_RANDOM_R2                   1003
#define IDC_PREF_KEYS_LIST              1003
#define IDC_HASH_ENC_BASE16             1003
#define IDC_CRYPT_CIPHER                1004
#define IDC_HASH_ENC_BASE64             1004
#define IDC_RANDOM_R3                   1004
#define IDC_PREF_KEYS_LABEL             1004
#define IDC_CRYPT_MODE                  1005
#define IDC_HASH_USE_KEY                1005
#define IDC_RANDOM_R4                   1005
#define IDC_PREF_KEYS_VALUE             1005
#define IDC_CRYPT_STATIC_PASSWORD       1006
#define IDC_HASH_KEY                    1006
#define IDC_RANDOM_R5                   1006
#define IDC_PREF_KEYS_ADD               1006
#define IDC_HASH_KEYRADIO1              1006
#define IDC_CRYPT_PASSWORD              1007
#define IDC_PREF_KEYS_DEL               1007
#define IDC_HASH_KEYRADIO2              1007
#define IDC_RANDOM_R6                   1007
#define IDC_CRYPT_SALT                  1008
#define IDC_PREF_KEYS_RANDOM            1008
#define IDC_HASH_KEYEDIT                1008
#define IDC_CRYPT_CIPHER2               1008
#define IDC_CRYPT_CIPHER_TYPE           1008
#define IDC_CRYPT_SALT_BYTES            1009
#define IDC_PREF_BASE64_LV              1009
#define IDC_HASH_HELP_ENC               1009
#define IDC_PREF_BASE64_LINELEN         1009
#define IDC_CRYPT_STATIC_PASSWORD2      1009
#define IDC_CRYPT_SALT_SPIN             1010
#define IDC_PREF_BASE64_LV_SPIN         1010
#define IDC_HASH_HELP_HASH              1010
#define IDC_CRYPT_HELP_ENC              1010
#define IDC_PREF_BASE64_LINELEN_SPIN    1010
#define IDC_CRYPT_KEY_PBKDF2            1011
#define IDC_PREF_HEX_SPACES             1011
#define IDC_HASH_HELP_KEY               1011
#define IDC_CRYPT_HELP_ENC2             1011
#define IDC_CRYPT_HELP_CIPHER           1011
#define IDC_CRYPT_KEY_BCRYPT            1012
#define IDC_PREF_HEX_LOWERCASE          1012
#define IDC_CRYPT_HELP_MODE             1012
#define IDC_PREF_BASE16_LOWERCASE       1012
#define IDC_CRYPT_KEY_SCRYPT            1013
#define IDC_PREF_HEX_UPPERCASE          1013
#define IDC_PREF_BASE16_UPPERCASE       1013
#define IDC_CRYPT_PBKDF2_HASH           1014
#define IDC_PREF_HEX_LV                 1014
#define IDC_PREF_BASE16_LINELEN         1014
#define IDC_CRYPT_PBKDF2_ITER           1015
#define IDC_PREF_HEX_LV_SPIN            1015
#define IDC_PREF_BASE16_LINELEN_SPIN    1015
#define IDC_CRYPT_PBKDF2_ITER_SPIN      1016
#define IDC_PREF_EOL_WINDOWS            1016
#define IDC_CRYPT_BCRYPT_ITER           1017
#define IDC_PREF_EOL_UNIX               1017
#define IDC_CRYPT_BCRYPT_ITER_SPIN      1018
#define IDC_PREF_HELP_FILES             1018
#define IDC_PREF_HELP                   1018
#define IDC_CRYPT_SCRYPT_N              1019
#define IDC_PREF_OK                     1019
#define IDC_CRYPT_SCRYPT_R              1020
#define IDC_PREF_HELP_FILES2            1020
#define IDC_PREF_HELP_KEYS              1020
#define IDC_CRYPT_CIPHER_KEY            1020
#define IDC_CRYPT_SCRYPT_P              1021
#define IDC_CRYPT_CIPHER_KEY2           1021
#define IDC_CRYPT_CIPHER_IV             1021
#define IDC_CONVERT_FROM_ASCII          1021
#define IDC_CRYPT_SCRYPT_R_SPIN         1022
#define IDC_CONVERT_FROM_BASE16         1022
#define IDC_CRYPT_SCRYPT_P_SPIN         1023
#define IDC_CONVERT_FROM_BASE32         1023
#define IDC_CRYPT_SCRYPT_N_SPIN         1024
#define IDC_CONVERT_FROM_BASE64         1024
#define IDC_CRYPT_HMAC_ENABLE           1025
#define IDC_CRYPT_HELP_SALT             1025
#define IDC_CRYPT_HMAC_HASH             1026
#define IDC_CRYPT_HELP_PBKDF2           1026
#define IDC_CRYPT_HELP_IV               1026
#define IDC_CONVERT_TO_ASCII            1026
#define IDC_CRYPT_AUTH_KEY_LIST         1027
#define IDC_CRYPT_HELP_BCRYPT           1027
#define IDC_CONVERT_TO_BASE16           1027
#define IDC_CRYPT_AUTH_KEY_PRESET       1028
#define IDC_CRYPT_HELP_SALT2            1028
#define IDC_CRYPT_HELP_SCRYPT           1028
#define IDC_CONVERT_TO_BASE32           1028
#define IDC_PREF_BASE32_LOWERCASE       1028
#define IDC_CRYPT_AUTH_KEY_CUSTOM       1029
#define IDC_PREF_BASE32_UPPERCASE       1029
#define IDC_CRYPT_AUTH_KEY_VALUE        1030
#define IDC_RADIO10                     1030
#define IDC_CONVERT_TO_BASE64           1030
#define IDC_PREF_BASE32_LINELEN         1030
#define IDC_CHECK1                      1031
#define IDC_CONVERT_LINEBREAKS          1031
#define IDC_PREF_BASE32_LINELEN_SPIN    1031
#define IDC_CRYPT_ENC_LINEBREAK         1031
#define IDC_CRYPT_IV_RANDOM             1032
#define IDC_CRYPT_HELP_HMAC             1032
#define IDC_EDIT1                       1032
#define IDC_CONVERT_LINELENGTH          1032
#define IDC_CONVERT_LINELEN             1032
#define IDC_CRYPT_ENC_LINELEN           1032
#define IDC_INITDATA_SALT               1032
#define IDC_CRYPT_IV_KEY                1033
#define IDC_SPIN1                       1033
#define IDC_CONVERT_LINELEN_SPIN        1033
#define IDC_CRYPT_ENC_LINELEN_SPIN      1033
#define IDC_INITDATA_IV                 1033
#define IDC_CRYPT_IV_ZERO               1034
#define IDC_CONVERT_LB_WINDOWS          1034
#define IDC_EDIT3                       1034
#define IDC_INITDATA_TAG                1034
#define IDC_ABOUT_TEXT                  1035
#define IDC_CONVERT_LB_UNIX             1035
#define IDC_CONVERT_UPPERCASE           1036
#define IDC_CRYPT_CIPHER_INFO           1038
#define IDC_CRYPT_ENC_BASE16            1039
#define IDC_CRYPT_ENC_BASE32            1040
#define IDC_CRYPT_ENC_HELP              1041
#define IDC_CRYPT_ENC_LB_WIN            1042
#define IDC_CRYPT_ENC_LB_UNIX           1043
#define IDC_CRYPT_ENC_UPPERCASE         1044
#define IDC_CRYPT_HELP_KEYALGO          1045
#define IDC_HASH_ENC_BASE32             1046
#define IDC_CHECK2                      1047
#define IDC_CRYPT_ADDHEADER             1047
#define IDC_CRYPT_AUTH_KEY_SHOW         1051
#define IDC_COPY						1052
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1048
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
